server:
  port: 9000
  context-path: /config-client
  display-name: ConfigClient

management:
  security:
    enabled: false
    
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
