---
spring:
  profiles: eureka-server1
    
server:
  address: 0.0.0.0
  port: 8761
  display-name: EurekaServer
  
management:
  context-path: /admin
  security:
    enabled: false
    
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
    
eureka:
  instance:
    hostname: eureka-server1
    prefer-ip-address: false
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server2:8762/eureka/
      
---
spring:
  profiles: eureka-server2

server:
  address: 0.0.0.0
  port: 8762
  display-name: EurekaServer
  
management:
  context-path: /admin
  security:
    enabled: false
    
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
    
eureka:
  instance:
    hostname: eureka-server2
    prefer-ip-address: false
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/
      