---
spring:
  profiles: config-server1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellscorpionxp/config-repo.git
          basedir: ${user.home}/.config
          clone-on-start: true
          force-pull: true
        health:
          repositories:
            foo-db:
              name: foo
              profiles: db
            foo-development-db:
              name: foo
              profiles: development-db
            samplebackendservice-development:
              name: samplebackendservice
              profiles: development
              
server:
  address: 0.0.0.0
  port: 8888
  display-name: ConfigServer
  
management:
  context-path: /admin
  security:
    enabled: false
    
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
    
#logging:
#  config: classpath:log4j2-spring.json
  
---
spring:
  profiles: config-server2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hellscorpionxp/config-repo.git
          basedir: ${user.home}/.config
          clone-on-start: true
          force-pull: true
        health:
          repositories:
            foo-db:
              name: foo
              profiles: db
            foo-development-db:
              name: foo
              profiles: development-db
            samplebackendservice-development:
              name: samplebackendservice
              profiles: development
              
server:
  address: 0.0.0.0
  port: 8889
  display-name: ConfigServer
  
management:
  context-path: /admin
  security:
    enabled: false
    
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
    
#logging:
#  config: classpath:log4j2-spring.json
  